image: alpine/latest
packages:
  - npm
secrets:
  - f8cf1511-aef8-444b-ae25-e088b659bc79
environment:
  site: weather.app.5ls.de
tasks:
  - v2-only: |
      cd  $site/
      if [ "$(git rev-parse origin/v2)" != "$(git rev-parse HEAD)" ]; then
        complete-build;
      fi

  - install: |
      sudo npm install --loglevel=error --global wrangler

  - publish: |
      . ~/.cloudflaresecrets
      rm -rf $site/.git
      npx wrangler pages publish $site --project-name=$(echo $site | sed -e "s/\./-/g")
