title: Wetter
url: https://wetter.app.5ls.de

collections:
  deutschland:
    output: true
    permalink: /:title/
  welt:
    output: true
    permalink: /:title/


defaults:
  - scope:
      path: ""
      type: "deutschland"
    values:
      layout: "ort-default"
      land: de
  - scope:
      path: ""
      type: "welt"
    values:
      layout: "ort-default"
      meteoblue: "disabled"


exclude:
  - CNAME

timezone: Europe/Berlin
