title: Wetter
url: https://wetter.app.5ls.de

collections:
  ort:
    output: true
    permalink: /:title/
    order:
      - muenchen.md
      - stoetten.md
  aktuell:
    output: true
    permalink: /:title/aktuell/


defaults:
  - scope:
      path: ""
      type: "ort"
    values:
      layout: "ort"
  - scope:
      path: ""
      type: "aktuell"
    values:
      layout: "aktuell"
 

exclude:
  - CNAME

timezone: Europe/Berlin
