title: Wetter
url: https://wetter.app.5ls.de

collections:
  ort:
    output: true
    permalink: /:title/


defaults:
  - scope:
      path: ""
      type: "ort"
    values:
      layout: "ort"
 

exclude:
  - CNAME

timezone: Europe/Berlin
